### PR TITLE
Optimize checking order & allow blackbox arrays

### PR DESCRIPTION
**Pull request by jlsjonas**

### CODE REVIEW

**Comment by sebakerckhof** [comment]
This only handles cleaning, but validation would still fail. You would also need to adjust the validation logic, add the relevant tests and update the blackbox section in the readme.

**Comment by sebakerckhof** [comment]
I've added the necessary tests

**Comment by jlsjonas** [comment]
> This only handles cleaning, but validation would still fail. You would also need to adjust the validation logic, add the relevant tests and update the blackbox section in the readme.

Adjusted the validation logic & generalized the blackbox section in readme
(our use-case was with a custom type so validation didn't fail :) )

**Comment by sebakerckhof** [comment]
Published as 2.1.0. Thanks

**Pull request merged**
